/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as InformacoesJuridicasRouteImport } from './routes/informacoes-juridicas'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as AreasDeAtuacaoRouteImport } from './routes/areas-de-atuacao'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacoesJuridicasRoute = InformacoesJuridicasRouteImport.update({
  id: '/informacoes-juridicas',
  path: '/informacoes-juridicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeAtuacaoRoute = AreasDeAtuacaoRouteImport.update({
  id: '/areas-de-atuacao',
  path: '/areas-de-atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/artigos': typeof ArtigosRoute
  '/informacoes-juridicas': typeof InformacoesJuridicasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/artigos': typeof ArtigosRoute
  '/informacoes-juridicas': typeof InformacoesJuridicasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/artigos': typeof ArtigosRoute
  '/informacoes-juridicas': typeof InformacoesJuridicasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas-de-atuacao'
    | '/artigos'
    | '/informacoes-juridicas'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areas-de-atuacao'
    | '/artigos'
    | '/informacoes-juridicas'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/areas-de-atuacao'
    | '/artigos'
    | '/informacoes-juridicas'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasDeAtuacaoRoute: typeof AreasDeAtuacaoRoute
  ArtigosRoute: typeof ArtigosRoute
  InformacoesJuridicasRoute: typeof InformacoesJuridicasRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacoes-juridicas': {
      id: '/informacoes-juridicas'
      path: '/informacoes-juridicas'
      fullPath: '/informacoes-juridicas'
      preLoaderRoute: typeof InformacoesJuridicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-atuacao': {
      id: '/areas-de-atuacao'
      path: '/areas-de-atuacao'
      fullPath: '/areas-de-atuacao'
      preLoaderRoute: typeof AreasDeAtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasDeAtuacaoRoute: AreasDeAtuacaoRoute,
  ArtigosRoute: ArtigosRoute,
  InformacoesJuridicasRoute: InformacoesJuridicasRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
