/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as InformacoesJuridicasRouteImport } from './routes/informacoes-juridicas'
import { Route as DadosProfissionaisRouteImport } from './routes/dados-profissionais'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as AreasDeAtuacaoRouteImport } from './routes/areas-de-atuacao'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacoesJuridicasRoute = InformacoesJuridicasRouteImport.update({
  id: '/informacoes-juridicas',
  path: '/informacoes-juridicas',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosProfissionaisRoute = DadosProfissionaisRouteImport.update({
  id: '/dados-profissionais',
  path: '/dados-profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeAtuacaoRoute = AreasDeAtuacaoRouteImport.update({
  id: '/areas-de-atuacao',
  path: '/areas-de-atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/artigos': typeof ArtigosRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/dados-profissionais': typeof DadosProfissionaisRoute
  '/informacoes-juridicas': typeof InformacoesJuridicasRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/artigos': typeof ArtigosRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/dados-profissionais': typeof DadosProfissionaisRoute
  '/informacoes-juridicas': typeof InformacoesJuridicasRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/artigos': typeof ArtigosRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/dados-profissionais': typeof DadosProfissionaisRoute
  '/informacoes-juridicas': typeof InformacoesJuridicasRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas-de-atuacao'
    | '/artigos'
    | '/aviso-legal'
    | '/dados-profissionais'
    | '/informacoes-juridicas'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areas-de-atuacao'
    | '/artigos'
    | '/aviso-legal'
    | '/dados-profissionais'
    | '/informacoes-juridicas'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/areas-de-atuacao'
    | '/artigos'
    | '/aviso-legal'
    | '/dados-profissionais'
    | '/informacoes-juridicas'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasDeAtuacaoRoute: typeof AreasDeAtuacaoRoute
  ArtigosRoute: typeof ArtigosRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  DadosProfissionaisRoute: typeof DadosProfissionaisRoute
  InformacoesJuridicasRoute: typeof InformacoesJuridicasRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacoes-juridicas': {
      id: '/informacoes-juridicas'
      path: '/informacoes-juridicas'
      fullPath: '/informacoes-juridicas'
      preLoaderRoute: typeof InformacoesJuridicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados-profissionais': {
      id: '/dados-profissionais'
      path: '/dados-profissionais'
      fullPath: '/dados-profissionais'
      preLoaderRoute: typeof DadosProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-atuacao': {
      id: '/areas-de-atuacao'
      path: '/areas-de-atuacao'
      fullPath: '/areas-de-atuacao'
      preLoaderRoute: typeof AreasDeAtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasDeAtuacaoRoute: AreasDeAtuacaoRoute,
  ArtigosRoute: ArtigosRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  DadosProfissionaisRoute: DadosProfissionaisRoute,
  InformacoesJuridicasRoute: InformacoesJuridicasRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
